### ISSUE TITLE
使用目录浏览功能的时候，话说能不能有个WebDAV标记模块

### ISSUE THREAD

**Issue by 1265578519** [keengo99/kangle#15]
话说能不能有个WebDAV标记模块，这样可以用dir匹配模块匹配某个文件夹实现可写
可同时写入权限，让其来读写文件，实现挂载到Windows系统文件管理器中。

**Comment by keengo99** [comment]
这个可以通过写模块的方式来实现。

**Comment by 1265578519** [comment]
这个模块是官方负责开发还是让自己去开发。。
