### ISSUE TITLE
有人反馈遇到多个https站点，未部署证书的http站点使用https访问时提示ssl证书不安全问题

### ISSUE THREAD

**Issue by 1265578519** [keengo99/kangle#16]
我给他回应
目前版本因为要支持sni协议来识别不同的站点，这样才能实现一台服务器支持多个https站点（现在没有强制校验证书是否吊销在输出给用户的功能选项，可以汇报给官方做个标记模块来实现），如果未部署证书的站点则会输出全局默认证书。
个人建议可以对不需要https的站点进行关闭https端口来实现，同时为了您的站点安全性着想，请尽快升级到https
最简单的办法是，kangle新建主机功能来创建多个虚拟主机，在绑定处进行绑定端口，格式如下，尾部s代表绑定启用并且打开相应的https端口
!*:80
!*:443s
!*:10001
!*:10002
还有其他方法描述起来比较复杂，个人建议是用虚拟主机这种形式去区分多个CDN站点，此时在次对未启用https的站点使用https访问，则不会获得到网站数据
如果使用的是ep来控制kangle，则登录easypanel的admin控制面板后台，点击左侧网站管理-所有网站-点击修改按钮，其它高级选项点击展开，点击端口处输入80,443s代表对该站点启用http，仅输入80代表关闭https，如果留空则跟随kangle全局设置

所以，要不要出一个标记模块，例如模块名为check_ssl_reject
提供四个可勾选选项，第一个，检查源站证书是否吊销，第二个，检查kangle自身边缘节点证书是否被吊销，第三个，检查sni字符串是否和证书可使用名称一致，第四个，检查证书文件过期时间是否在有效期内

**Comment by keengo99** [comment]
因为443端口是共享的，只要有一个站点要开，443就打开了。
然后如果你这个虚拟主机没有部署证书，肯定就会提示不安全。

**Comment by 1265578519** [comment]
> 因为443端口是共享的，只要有一个站点要开，443就打开了。 然后如果你这个虚拟主机没有部署证书，肯定就会提示不安全。

主要可以参考cloudflare等等，都会进行校验证书，不会输出其它主机下的证书。

**Comment by 1265578519** [comment]
官方会做模块会解决这个问题吗？
简单说就是空间1开了https，空间2站点未部署https然后用https访问输出空间1的证书，需要用模块去校验证书
