### ISSUE TITLE
Linux有办法进一步优化提高kangle线程切换的处理能力吗？

### ISSUE THREAD

**Issue by 1265578519** [keengo99/kangle#18]
其他程序跑的，CPU 30%，kangle 280%
![N86E69XGP)P9(9JUN{DNHUD](https://user-images.githubusercontent.com/6442439/176976212-c1736f5c-c489-413d-a4bb-602efb89600f.png)
![@BXEBH~EKY~9@R{S9VK7L$9](https://user-images.githubusercontent.com/6442439/176976238-62d49246-ff1d-46b4-8499-8239266a520b.png)

每个线程的处理内容
![GHH0ILZ_6 N{TZ%DFA2}6OC](https://user-images.githubusercontent.com/6442439/176976276-78b5abd6-ec18-4a2e-b0b9-53e2086f3e06.png)
![VFIKXH)N$B%13(D5_ 9`3U4](https://user-images.githubusercontent.com/6442439/176976280-3016c63d-31dd-49ca-8bb2-0aa050cfed31.png)
![LOK862F)@LKAM(696U@8J{D](https://user-images.githubusercontent.com/6442439/176976283-bae16964-857a-4aef-b781-4a7c87f0d493.png)
![3~_VK$}AP)NMGTBJF7L~LAX](https://user-images.githubusercontent.com/6442439/176976290-4830b974-d8c7-43ee-acf8-f9090ed50dd3.png)

应该是和线程数有关系，
默认0的情况下分配8个，占用280%，
改成1就占用97%
改成16占用380%
改成32占用430%
猜测：因为更多的线程，带来的是不必要的线程切换延迟导致的CPU额外增长，并不能提高性能，反而会导致CPU浪费增加使用率，所以保持"工作线程数"默认值为0以便自动调整。
不知道有没有办法优化降低到和那程序一样，同连接数负载情况，30%的使用率。
![CTLM$PP SOJ$513C$9NR`H0](https://user-images.githubusercontent.com/6442439/176976317-116cd1ab-3bc4-4da5-977b-ba36f3935b6b.png)

补充下issues，今天也是偶然刷到个视频，也算一个CPU占用高的案例
https://www.bilibili.com/video/BV18U4y1B7nA
https://www.bilibili.com/read/cv17521097
苦于没有分析是什么占用CPU的工具，，看视频来说，nginx有perf来分析

不过总体来说，，，无伤大雅，至少不是CPU死锁导致的死循环100%占用，本issues就是想找个视频上，火焰图之类的分析工具，以便快速知道CPU消耗在什么上面。虽然可以用bt切换线程来看，这样就知道每个线程在干什么，但是感觉bt不是太详细和不易懂。这还好了，，，一般人，服务器吃CPU，都不知道是什么原因导致的，他们至少还找出来了，视频上发现是lua编译器的问题，引起代码bug导致nginx死掉。

**Comment by keengo99** [comment]
这是哪个版本？

**Comment by 1265578519** [comment]
> 这是哪个版本？

3.5.21.16
