### ISSUE TITLE
清理缓存时候如果经过反代重写了，清理时候要写重写之前的域名才生效

### ISSUE THREAD

**Issue by 1265578519** [keengo99/kangle#2]
清理缓存时候如果经过反代重写了，清理时候要写重写之前的域名才生效
![image](https://user-images.githubusercontent.com/6442439/154853869-90689b5f-2dd4-44eb-aa00-32526470c3b3.png)
/core.whm?whm_call=clean_cache&url=3https://raw.githubusercontent.com/ 这个接口清缓存有bug..
rewrite的情况，，清理访问域名github.itzmx.com无效，要清理对方的域名raw.githubusercontent.com才能清除缓存成功

**Comment by keengo99** [comment]
缓存就是以反代之前的url为key.
所以经过重写后，肯定要以重写之前的url为key来清理。
