### ISSUE TITLE
源码编译错误

### ISSUE THREAD

**Issue by phrnet** [keengo99/kangle#20]
`-- Build files have been written to: /root/kangle/2/kangle/build
[root@app-srs-167 build]# make
Scanning dependencies of target khttpd
[  0%] Building CXX object khttpd/CMakeFiles/khttpd.dir/src/KAutoBuffer.cpp.o
[  0%] Building CXX object khttpd/CMakeFiles/khttpd.dir/src/KDechunkContext.cpp.o
In file included from /root/kangle/2/kangle/khttpd/include/KDechunkContext.h:4:0,
                 from /root/kangle/2/kangle/khttpd/src/KDechunkContext.cpp:1:
/root/kangle/2/kangle/khttpd/include/KDechunkEngine.h:35:73: error: invalid use of 'auto'
  static constexpr auto status_read_chunk_size{ static_cast<uint32_t>(0) };
                                                                         ^
/root/kangle/2/kangle/khttpd/include/KDechunkEngine.h:36:67: error: invalid use of 'auto'
  static constexpr auto status_read_end{ static_cast<uint32_t>(-1) };
                                                                   ^
/root/kangle/2/kangle/khttpd/include/KDechunkEngine.h:37:68: error: invalid use of 'auto'
  static constexpr auto status_read_last{ static_cast<uint32_t>(-2) };
                                                                    ^
/root/kangle/2/kangle/khttpd/include/KDechunkEngine.h:38:67: error: invalid use of 'auto'
  static constexpr auto status_is_ended{ static_cast<uint32_t>(-3) };
                                                                   ^
/root/kangle/2/kangle/khttpd/include/KDechunkEngine.h:39:68: error: invalid use of 'auto'
  static constexpr auto status_is_failed{ static_cast<uint32_t>(-4) };
                                                                    ^
make[2]: *** [khttpd/CMakeFiles/khttpd.dir/src/KDechunkContext.cpp.o] Error 1
make[1]: *** [khttpd/CMakeFiles/khttpd.dir/all] Error 2
make: *** [all] Error 2
`

另外 新版的二进制文件啥时候出呀?
还有商业版用户期待更新 还有机会吗?

**Comment by phrnet** [comment]
-- Build files have been written to: /root/kangle/2/kangle/build
[root@app-srs-167 build]# make
Scanning dependencies of target khttpd
[  0%] Building CXX object khttpd/CMakeFiles/khttpd.dir/src/KAutoBuffer.cpp.o
[  0%] Building CXX object khttpd/CMakeFiles/khttpd.dir/src/KDechunkContext.cpp.o
In file included from /root/kangle/2/kangle/khttpd/include/KDechunkContext.h:4:0,
                 from /root/kangle/2/kangle/khttpd/src/KDechunkContext.cpp:1:
/root/kangle/2/kangle/khttpd/include/KDechunkEngine.h:35:73: error: invalid use of 'auto'
  static constexpr auto status_read_chunk_size{ static_cast<uint32_t>(0) };
                                                                         ^
/root/kangle/2/kangle/khttpd/include/KDechunkEngine.h:36:67: error: invalid use of 'auto'
  static constexpr auto status_read_end{ static_cast<uint32_t>(-1) };
                                                                   ^
/root/kangle/2/kangle/khttpd/include/KDechunkEngine.h:37:68: error: invalid use of 'auto'
  static constexpr auto status_read_last{ static_cast<uint32_t>(-2) };
                                                                    ^
/root/kangle/2/kangle/khttpd/include/KDechunkEngine.h:38:67: error: invalid use of 'auto'
  static constexpr auto status_is_ended{ static_cast<uint32_t>(-3) };
                                                                   ^
/root/kangle/2/kangle/khttpd/include/KDechunkEngine.h:39:68: error: invalid use of 'auto'
  static constexpr auto status_is_failed{ static_cast<uint32_t>(-4) };
                                                                    ^
make[2]: *** [khttpd/CMakeFiles/khttpd.dir/src/KDechunkContext.cpp.o] Error 1
make[1]: *** [khttpd/CMakeFiles/khttpd.dir/all] Error 2
make: *** [all] Error 2

**Comment by phrnet** [comment]
![image](https://user-images.githubusercontent.com/16816735/179940610-6ac204a4-66e5-4ca6-9751-64e297b5b234.png)

**Comment by 1265578519** [comment]
![ZMK${PJK$47B19ZXYFFH3EO](https://user-images.githubusercontent.com/6442439/179958990-ae6eba12-2bf5-44d8-9ba5-8354d9c72e2b.png)
3.5.21.4我都编译不上了，不知道什么原因

**Comment by keengo99** [comment]
你什么坏境啊？

**Comment by 1265578519** [comment]
我是centos7下编译错误，不知道楼主是什么

**Comment by phrnet** [comment]
跟小樱一样 centos7

**Comment by keengo99** [comment]
centos 7编译的问题，应该是好了！
