### ISSUE TITLE
windows版本启动报错SSL use certificate file []: Error: error:02001000:system library:fopen:system library

### ISSUE THREAD

**Issue by 1265578519** [keengo99/kangle#23]
SSL use certificate file []: Error: error:02001000:system library:fopen:system library
Cann't init ssl context certificate=[],certificate_key=[]

这串报错怎么消除

**Comment by keengo99** [comment]
这个是没有配置成功ssl的证书文件

**Comment by 1265578519** [comment]
> 这个是没有配置成功ssl的证书文件

有部署的呀，https都是正常访问的，你看看是为什么
[kangle for windows 绿色版_2.zip](https://github.com/keengo99/kangle/files/10235926/kangle.for.windows._2.zip)
