### ISSUE TITLE
虚拟主机信息不支持存到vhs.db吗

### ISSUE THREAD

**Issue by flucont** [keengo99/kangle#30]
旧版本kangle都支持的，但是这个版本却无法使用。

已经修改好配置文件，如下：
`<CreateProcess>AsUser</CreateProcess>
<vhs>
<vh_database
driver='bin/vhs_sqlite.so'
dbname='etc/vhs.db'
/>
</vhs>
`
vhs.db是沿用旧版本kangle生成的
在虚拟主机列表无法识别到vhs.db里面的虚拟主机。

**Comment by keengo99** [comment]
把vhs.db发上来，我测试一下看看！

**Comment by keengo99** [comment]
已经提交了补丁，修复了这个问题！
