### ISSUE TITLE
帮群友反馈下，Linux下 centos8,debian11,ubuntu20都无法编译成功

### ISSUE THREAD

**Issue by 1265578519** [keengo99/kangle#31]
编译报错图
![BB598`A6XZP8G}JMYG2QB03](https://user-images.githubusercontent.com/6442439/212045349-1e3cea55-e315-4811-8a76-98cda589ba9a.png)

确定目录下有boringssl
![GW6$RUVN(VC7(%EERVNU_SL](https://user-images.githubusercontent.com/6442439/212045375-9d2fe74c-aff0-45c8-9075-a22e3b7988d7.png)

**Comment by keengo99** [comment]
cmake命令是什么？

**Comment by 1265578519** [comment]
> cmake命令是什么？

他说用的readme上的命令

**Comment by keengo99** [comment]
dev分支已经解决了这个问题！

**Comment by keengo99** [comment]
已经合并到main分支

**Comment by 1265578519** [comment]
![O0M7$CYM8})BNBUBNN@A}CW](https://user-images.githubusercontent.com/6442439/214019485-3281abd9-4a0b-4e5b-89ed-3f358f15442f.png)
这是他最新出的编译错误
