### ISSUE TITLE
连接详情能否增加一个状态显示 客户端已断开连接（Canceled）服务器未发送数据，客户端就已经重置断开连接

### ISSUE THREAD

**Issue by 1265578519** [keengo99/kangle#32]
连接详情能否增加一个状态显示 客户端已断开连接（Canceled）服务器未发送数据，客户端就已经重置断开连接

类似cloudflare的后台，可以观察出现连接重置的情况。
![image](https://user-images.githubusercontent.com/6442439/212467028-6541ce18-15a3-41f7-8c7a-d9f405449f4e.png)

**Comment by keengo99** [comment]
可以记录在日志里面，通过分析日志观察。

**Comment by 1265578519** [comment]
![image](https://user-images.githubusercontent.com/6442439/212547707-00379c94-a558-4851-8c33-77696bd1c051.png)
日志里也可以，就是要用ssh去操作，没连接详情这么直观了，我感觉连接详情里unset外另外加个Canceled状态显示应该不会吃性能吧。
