### ISSUE TITLE
有没有办法不使用iptables防火墙，让kangle处理netfilter流量转发实现透明反代

### ISSUE THREAD

**Issue by 1265578519** [keengo99/kangle#34]
有没有办法不使用iptables防火墙，让kangle处理netfilter流量转发实现透明反代

优势：
1.不需要监听TCP端口，外部扫描端口显示已关闭。
2.对于TCP游戏流量，源站可以获取到真实ip地址，不会显示成节点ip。

**Comment by keengo99** [comment]
没有办法。
