### ISSUE TITLE
kangle编译失败

### ISSUE THREAD

**Issue by hiniok** [keengo99/kangle#37]
[ 45%] Building CXX object CMakeFiles/kangle.dir/src/KAccess.cpp.o
In file included from /root/kangle/include/KHttpManage.h:12:0,
                 from /root/kangle/module/whm/whmdso/core/core.cpp:32:
/root/kangle/include/KPathHandler.h:11:2: error: ‘_NODISCARD’ does not name a type
  _NODISCARD constexpr int operator()(const _Ty* _Left, const _Ty* _Right) const {
  ^
/root/kangle/include/KPathHandler.h: In member function ‘T KPathHandler<T, CMP>::remove(const char*, size_t)’:
/root/kangle/include/KPathHandler.h:163:8: error: ‘child_node’ was not declared in this scope
    if (child_node->empty()) {
        ^
In file included from /root/kangle/include/HttpFiber.h:6:0,
                 from /root/kangle/src/HttpFiber.cpp:2:
/root/kangle/include/KPathHandler.h:11:2: error: ‘_NODISCARD’ does not name a type
  _NODISCARD constexpr int operator()(const _Ty* _Left, const _Ty* _Right) const {
  ^
/root/kangle/include/KPathHandler.h: In member function ‘T KPathHandler<T, CMP>::remove(const char*, size_t)’:
/root/kangle/include/KPathHandler.h:163:8: error: ‘child_node’ was not declared in this scope
    if (child_node->empty()) {
        ^
In file included from /root/kangle/src/HttpFiber.cpp:2:0:
/root/kangle/include/HttpFiber.h: In function ‘KGL_RESULT handle_request(KPathHandler<_KGL_RESULT (*)(kgl_str_t*, void*, KHttpRequest*, _kgl_input_stream*, _kgl_output_stream*), CMP>&, void*, KHttpRequest*, kgl_input_stream*, kgl_output_stream*)’:
/root/kangle/include/HttpFiber.h:55:15: error: invalid use of incomplete type ‘class KHttpRequest’
  auto url = rq->sink->data.url;
               ^
In file included from /root/kangle/src/HttpFiber.cpp:2:0:
/root/kangle/include/HttpFiber.h:8:7: error: forward declaration of ‘class KHttpRequest’
 class KHttpRequest;
       ^
In file included from /root/kangle/include/HttpFiber.h:6:0,
                 from /root/kangle/src/HttpCore.cpp:61:
/root/kangle/include/KPathHandler.h:11:2: error: ‘_NODISCARD’ does not name a type
  _NODISCARD constexpr int operator()(const _Ty* _Left, const _Ty* _Right) const {
  ^
/root/kangle/include/KPathHandler.h: In member function ‘T KPathHandler<T, CMP>::remove(const char*, size_t)’:
/root/kangle/include/KPathHandler.h:163:8: error: ‘child_node’ was not declared in this scope
    if (child_node->empty()) {
        ^
make[2]: *** [CMakeFiles/kangle.dir/module/whm/whmdso/core/core.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/kangle.dir/src/HttpCore.cpp.o] Error 1
In file included from /root/kangle/include/HttpFiber.h:6:0,
                 from /root/kangle/include/KVirtualHostProcess.h:19,
                 from /root/kangle/include/KCmdProcess.h:11,
                 from /root/kangle/include/KProcessManage.h:22,
                 from /root/kangle/include/KCmdPoolableRedirect.h:16,
                 from /root/kangle/include/KAcserverManager.h:24,
                 from /root/kangle/src/KAccess.cpp:25:
/root/kangle/include/KPathHandler.h:11:2: error: ‘_NODISCARD’ does not name a type
  _NODISCARD constexpr int operator()(const _Ty* _Left, const _Ty* _Right) const {
  ^
/root/kangle/include/KPathHandler.h: In member function ‘T KPathHandler<T, CMP>::remove(const char*, size_t)’:
/root/kangle/include/KPathHandler.h:163:8: error: ‘child_node’ was not declared in this scope
    if (child_node->empty()) {
        ^
make[2]: *** [CMakeFiles/kangle.dir/src/HttpFiber.cpp.o] Error 1
make[2]: *** [CMakeFiles/kangle.dir/src/KAccess.cpp.o] Error 1
make[1]: *** [CMakeFiles/kangle.dir/all] Error 2
make: *** [all] Error 2

**Comment by 1265578519** [comment]
一群友也有这个错误
![O33_92O03O_(E~P}3AR7(%S](https://user-images.githubusercontent.com/6442439/218426782-a84937f6-c944-40b0-9e96-b57ff2575dfd.png)

**Comment by keengo99** [comment]
修复了！

**Comment by 1265578519** [comment]
真的有修复吗？一个群十几个人，没有人成功编译上过，都是各种报错。
