### ISSUE TITLE
新版的已经没有ant_cc模块了?

### ISSUE THREAD

**Issue by phrnet** [keengo99/kangle#39]
编译了一个3.6的 发现CC防火墙没有了 
这个需要时怎么添加?
ps:我是商业版用户 正儿八经买的得那种

**Comment by keengo99** [comment]
3.6目前还处于开发阶段，不要用于生产，anti_cc已经模块化了。

**Comment by phrnet** [comment]
anti_cc模块化编译有吗还是需要自行编译 没有找到相关内容

**Comment by keengo99** [comment]
https://gitee.com/keengo/kwaf
