### ISSUE TITLE
缓存总数存在对不上的情况

### ISSUE THREAD

**Issue by 1265578519** [keengo99/kangle#4]
kangle如果因为用尽磁盘超过95%的情况，自动清理缓存数量，会导致总数不正确
或者是因为内存用尽达到5G设置值引起，暂未知是哪个触发BUG

例如
缓存总数        4043580
内存缓存        888267        5.00G
磁盘缓存        3738863        2.65T

**Comment by keengo99** [comment]
缓存总数本来就不是你认为的 内存数+磁盘数=总数。
因为有一些缓存，是同时存在于内存和磁盘的。
