### ISSUE TITLE
kangle如何禁用https的ip地址访问，存在ddos安全隐患

### ISSUE THREAD

**Issue by 1265578519** [keengo99/kangle#44]
![image](https://user-images.githubusercontent.com/6442439/229304323-ea905222-7f3d-4160-a8b6-e921088c23fa.png)

例如在 https://search.censys.io/ 中可以得到真实源站ip地址信息
新购买的服务器，被censys全网扫描https ip，都有使用CDN保护不存在泄露ip情况，但是基本隔一天在去查询，censys就会轻松把真实ip和域名关联起来，因为对方会全网扫描世界上所有的ip地址。

完美效果
https://104.18.31.69/
和cf cdn一样，输出ERR_SSL_VERSION_OR_CIPHER_MISMATCH 信息，此时不会响应给浏览器任何证书信息，在交互证书之前就阻断了访问

同时如果请求头包含使用不同的host，也不应当输出其它域名的证书信息，希望做个请求控制模块加强一下
例子模块两个选项，加一个复选框
默认允许自签名等任意域名响应https  不允许跨https站点访问，强制要求校验和证书域名一致性  复选框不允许https直接访问ip

这个问题很早以前就提过，希望能解决下，因为今天看到有人发了视频把这种ddos攻击方法曝光出来了
https://www.bilibili.com/video/av951981641

早几年能想到的办法就和up一样，在ep里创建个站点空间，域名绑定处填写ip地址绑定，然后设置一个自定义证书，弄个错误的证书上去

**Comment by keengo99** [comment]
修复了没有发送sni时直接拒绝。而不会发送一个默认的证书。

**Comment by 1265578519** [comment]
需要一个开关。在一些特定的生产环境下，可能需要使用IP直接访问。

**Comment by keengo99** [comment]
可以配置的，默认没开，在listen中增加属性 reject_nosni='1'



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月30日(周四) 下午4:18
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [keengo99/kangle] kangle如何禁用https的ip地址访问，存在ddos安全隐患 (Issue #44)




 
需要一个开关。在一些特定的生产环境下，可能需要使用IP直接访问。
