### ISSUE TITLE
kangle进程在系统top中包含了si软中断的cpu使用率，如何排除不包含显示进去

### ISSUE THREAD

**Issue by 1265578519** [keengo99/kangle#45]
kangle进程在系统top中包含了si软中断的cpu使用率，如何排除不包含显示进去

这样的话，会异常显示出kangle的cpu占用率比较高，这部分应当是系统si占用，kangle错误包含si一并显示了
![image](https://user-images.githubusercontent.com/6442439/229759744-1d40ac25-60ac-4d81-a8d6-d45a4dfdad4b.png)

以前反馈过cpu占用比较高的情况，，，难道是这个导致的，不过就算减掉si也比opentracker高一些，到时候在花时间测试一下和opentracker的cpu使用率对比。

**Comment by keengo99** [comment]
是否包含si也不是kangle所能控制的
