### ISSUE TITLE
Debian编译出错

### ISSUE THREAD

**Issue by Jun198** [keengo99/kangle#46]
![微信截图_20230411230624](https://user-images.githubusercontent.com/76256558/231206554-4c97cd32-ef50-45dc-a907-425ae63361c5.png)

环境 : Debian 11
cmake版本 ：3.26.2

如果编译http2版本可以完成编译，如果是编译http3版本就是会卡在boringssl错误。

**Comment by keengo99** [comment]
应该修复了这个问题，你测试一下看看！

**Comment by Jun198** [comment]
重新拉取编译，测试编译通过
