### ISSUE TITLE
kangle支持SNI分流吗？

### ISSUE THREAD

**Issue by netcccyun** [keengo99/kangle#47]
类似于nginx的SNI分流功能，可以实现除了web服务之外，多个服务共用443端口
https://qoanty.github.io/2021/05/xray-nginx-sni/

**Comment by 1265578519** [comment]
没有看明白这文章讲的什么？是指nginx有bug吗？
如果是指多个域名公用一个443端口，那么kangle是支持的，能绑定上百万个域名没有问题
如果是指其它的话，要等官方来解答下

**Comment by keengo99** [comment]
现在还不支持sni分流功能。
