### ISSUE TITLE
3.6.0 windows 版本收到访问量比较大的流量经常性80监听端口丢失

### ISSUE THREAD

**Issue by 1265578519** [keengo99/kangle#52]
3.6.0 windows 版本收到访问量比较大的流量经常性80监听端口丢失

![image](https://github.com/keengo99/kangle/assets/6442439/833ddc1e-79bf-4404-b3fe-e329808491c8)

此处突然变成空白
![image](https://github.com/keengo99/kangle/assets/6442439/849a636e-9e54-4a1b-8a4b-d35877264bdf)

![image](https://github.com/keengo99/kangle/assets/6442439/0e3e4d7f-168c-4b14-b111-635065a89268)

出现问题后，无法自动恢复，必须执行重起kangle

**Comment by keengo99** [comment]
已经修复了，请测试！
