### ISSUE TITLE
请求控制loadavg匹配模块不起作用，无法获取到系统cpu负载

### ISSUE THREAD

**Issue by 1265578519** [keengo99/kangle#53]
请求控制loadavg匹配模块不起作用，无法获取到系统cpu负载

**Comment by xy3xy3** [comment]
我用的旧版本release3.5.21.16也是不行

**Comment by keengo99** [comment]
loadavg目前只获取到整数部分，小数部分完全忽略！

**Comment by xy3xy3** [comment]
> loadavg目前只获取到整数部分，小数部分完全忽略！

请问这个平均负载是多少分钟的平均，我这里一直为0，loadavg: >60(cur:0)
