### ISSUE TITLE
关于新版标记模块与匹配模块有所变动

### ISSUE THREAD

**Issue by JDKJD3432** [keengo99/kangle#56]
我发现新版标记模块没有param这个模块

post_file这个标记模块也没有，是新版本身就没有，需要自己编译，还是说淘汰掉了

而且之前name编号也没了，请问是需要自己编译还是说您已经淘汰掉了那些模块呢？

**Comment by JDKJD3432** [comment]
**对于新增的匹配与标记模块，是否有文档介绍**

**Comment by keengo99** [comment]
param和post_file准备移入主程序之外的动态库中实现。
name编号确实已经没有使用了，现在配置文件会更加智能按需加载变化部分。

**Comment by keengo99** [comment]
filter模块例子。https://gitee.com/keengo/kangle/tree/main/module/filter

**Comment by keengo99** [comment]
filter模块已完成，请测试！
