### ISSUE TITLE
能不能做一个每日自动编译，不然不知道怎么把那些代码怎么变成exe来用

### ISSUE THREAD

**Issue by 1265578519** [keengo99/kangle#57]
能不能做一个每日自动编译，不然不知道怎么把那些代码怎么变成exe来用

**Comment by nkxingxh** [comment]
我用 Jenkins 搞了个自动构建，启用了 **brotli 压缩**和 **HTTP3** 支持。
构建环境是 Linux，我在 Windows 环境构建时会找不到头文件 `pcre.h`

https://ci.stdio.run/job/kangle/

**Comment by mybove** [comment]
> 我用 Jenkins 搞了个自动构建，启用了 **brotli 压缩**和 **HTTP3** 支持。 构建环境是 Linux，我在 Windows 环境构建时会找不到头文件 `pcre.h`
> 
> https://ci.stdio.run/job/kangle/

请问这个怎么使用？我直接替换原来的用不了

**Comment by nkxingxh** [comment]
> > 我用 Jenkins 搞了个自动构建，启用了 **brotli 压缩**和 **HTTP3** 支持。 构建环境是 Linux，我在 Windows 环境构建时会找不到头文件 `pcre.h`
> > https://ci.stdio.run/job/kangle/
> 
> 请问这个怎么使用？我直接替换原来的用不了

之前的版本和现在的版本有一定区别，检查一下配置文件

**Comment by mybove** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，我已收到您的邮件，感谢您对我们工作的支持！谢谢！
