### ISSUE TITLE
反代chatgpt流式输出不是一个字一个输出

### ISSUE THREAD

**Issue by hlwqcc** [keengo99/kangle#58]
已设置flag no_buffer ，centos下测试是几个字几个字输出，体验不流畅。 windows下测试没有问题。

**Comment by 1265578519** [comment]
你Linux下是不是用了param标记模块，这个模块会把post数据缓冲到临时内存中

**Comment by hlwqcc** [comment]
使用get请求模拟流式输出也是不行的，windows下就没问题

**Comment by keengo99** [comment]
告诉我怎么重现！

**Comment by hlwqcc** [comment]
<?php
ini_set('max_execution_time', 0);
ob_start();
header('X-No-Buffer: 0');
header('Content-Type: text/event-stream; charset=utf-8');
$i = 1;
while($i < 10000) {
	echo $i . " ";
	$i++;
	usleep(50000);
	ob_flush();
	flush();
}

使用这一段PHP模拟流式输出，linux下是每次输出5个字，windows下正常是每次输出1个字

**Comment by keengo99** [comment]
已经修复了，请测试最新的。

**Comment by hlwqcc** [comment]
3.6编译测试没问题，但能否编译一个企业版3.5的最新版，把这个bug修复，谢谢

**Comment by keengo99** [comment]
你是什么系统？

**Comment by hlwqcc** [comment]
centos 7

**Comment by keengo99** [comment]
已经修复，换了一个写法，merge是c++ 17的。
