### ISSUE TITLE
kangle的目录浏览功能 url编码使用了不规范的GB2312，用unescape解析不出来，，应当先编码为UTF8在进行escape

### ISSUE THREAD

**Issue by 1265578519** [keengo99/kangle#6]
kangle的目录浏览功能 url编码使用了不规范的GB2312，用unescape解析不出来，，应当先编码为UTF8在进行escape
协议规范中确实写明了要UTF8来进行输出
Runtime Semantics

When a code unit to be included in a URI is not listed above or is not intended to have the special meaning sometimes given to the reserved code units, that code unit must be encoded. The code unit is transformed into its UTF-8 encoding, with surrogate pairs first converted from UTF-16 to the corresponding code point value. (Note that for code units in the range [0,127] this results in a single octet with the same value.) The resulting sequence of octets is then transformed into a String with each octet represented by an escape sequence of the form "%xx".

例如进入 新建文件夹，确认为kangle使用了GB2312
http://ip/%D0%C2%BD%A8%CE%C4%BC%FE%BC%D0/

对于web服务器，可以保持原有GB2312兼容访问对应路径，并且页面输出源码和复制链接输出时应当给予UTF8的链接

**Comment by keengo99** [comment]
这个主要是为了性能，系统给出的什么就直接编码什么了，没有去做转换。
再说这个功能用的人不多，如果要转换，必须像你说的，从url到物理文件的过程中还要考虑兼容性，就是gbk和utf-8都要支持。
而url到物理文件过程的使用频率就太高了，反而会影响性能。

**Comment by 1265578519** [comment]
我想到了个办法，在响应头部输出这样，应该不会影响性能
```
content-disposition: attachment; filename="UTF8编码的文件名.apk"
```
或者使用rfc5987，采用了filename* 在HTTP协议开发规范中确实有查到，应该可以解决问题
![image](https://user-images.githubusercontent.com/6442439/158374746-36d794ee-50c8-4287-b8d6-f62a06ddd19f.png)
*=编码两个’'文件名
大概就是这个意思了
https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers/Content-Disposition
https://datatracker.ietf.org/doc/html/rfc5987
```
Content-Disposition: attachment; filename*=UTF-8''%E3%80%8A%E4%BB%99%E5%89%91%E5%A5%87%E4%BE%A0%E4%BC%A0%E4%B8%83%E3%80%8B%EF%BC%88Chinese%20Paladin%20Sword%20and%20Fairy%207%EF%BC%89%E7%AB%A0%E8%8A%8215.mp4
```

**Comment by 1265578519** [comment]
单纯输出文件名视乎还是不行，，还是得标记模块加强，因为还有很多目录等等，，，
```
http://1.1.1.1/%5B%20%E9%AB%98%E6%B8%85%E5%89%A7%E9%9B%86%E7%BD%91%20www.BTHDTV.com%20%5D%E9%BB%91%E9%87%91%E9%A3%8E%E6%9A%B4%5B%E7%AC%AC13-14%E9%9B%86%5D%5B%E5%9B%BD%E8%AF%AD%E9%85%8D%E9%9F%B3+%E4%B8%AD%E6%96%87%E5%AD%97%E5%B9%95%5D.In.the.Storm.S01.2022.2160p.WEB-DL.H265.AAC.2Audio-CatWEB/In.the.Storm.S01E13.2022.2160p.WEB-DL.H265.AAC.2Audio-CatWEB.mkv
```
那
在换个思路，默认始终为utf-8标准规范化输出，客户端发起gb2312编码到服务器时，不进行同时兼容gbk处理，需要通过标记模块启用后，才去兼容gbk链接

**Comment by keengo99** [comment]
这个功能可以写扩展的形式支持。
