### ISSUE TITLE
谷歌推出新的压缩引擎，什么时候支持下zstd

### ISSUE THREAD

**Issue by 1265578519** [keengo99/kangle#65]
版本 123.0.2420.97 (正式版本) (64 位)
已经默认支持
Accept-Encoding:
gzip, deflate, br, zstd

压缩CPU效率是br的三倍
https://chromestatus.com/feature/6186023867908096

**Comment by keengo99** [comment]
更新支持zstd了。

**Comment by 1265578519** [comment]
如果报错
zstd.h: No such file or directory

安装压缩开发库并且重新编译
```
yum -y install libzstd-devel
```

**Comment by keengo99** [comment]
用zstd源码安装



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月21日(周二) 晚上7:21
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [keengo99/kangle] 谷歌推出新的压缩引擎，什么时候支持下zstd (Issue #65)




 
如果报错
 zstd.h: No such file or directory
 
安装压缩开发库并且重新编译
 yum -y install libzstd-devel

**Comment by keengo99** [comment]
这个要符合http协议的，客户端要发送accept-encoding，只能根据客户端指定的进行压缩



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月13日(周四) 晚上8:10
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [keengo99/kangle] 谷歌推出新的压缩引擎，什么时候支持下zstd (Issue #65)




 
有没有办法始终压缩，选择用gz，br，zstd之一，例如始终使用zstd压缩然后输出页面的选项，此时忽略浏览器标记头部
 而且有时候php页面输出明明有Content-Type: text/html，但是没有成功进行压缩

**Comment by 1265578519** [comment]
另一款http软件可以用编译参数来实现，启用编译参数后，可以总是使用zstd返回数据，一些环境下可能不需要考虑浏览器兼容性，都是直接app或者PC客户端，此时不需要考虑zstd以外的其它数据回应给用户端
FEATURES+=-DWANT_COMPRESSION_ZSTD
#FEATURES+=-DWANT_COMPRESSION_ZSTD_ALWAYS
LDFLAGS+=-lzstd
