### ISSUE TITLE
kangle是否会在节点进行gzip、br解压后在返回无压缩数据给用户？

### ISSUE THREAD

**Issue by 1265578519** [keengo99/kangle#67]
源站已经处理文件并且响应：
Content-Encoding: br

kangle节点作为边缘，然后给用户访问

用户端访问时，Accept-Encoding: gzip 声明未支持br，此时kangle是否会解压并且重新压缩成gzip返回，或者用户Accept-Encoding声明为空时，直接解压后的数据返回

如果在kangle上发生解压，过程是否在内存执行，是否会因为文件大小导致节点内存泄漏？有无办法禁用节点上的解压操作

测试，在源站存放300KB的文件，并且增加Content-Encoding: br响应头，此时用户端访问会产生400G的流量
[400Gbr.zip](https://github.com/user-attachments/files/16041570/400Gbr.zip)

目前已知cloudflare的CDN节点会解压400G文件并且返回给用户（用户端需在浏览器删除Accept-Encoding）
kangle上还没来得及测试一下，等会补一下kangle的结果，感觉应该可以配合identity_encoding模块来实现

**Comment by keengo99** [comment]
不会解压缩，再压缩另一种格式



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月29日(周六) 晚上11:59
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [keengo99/kangle] kangle是否会在节点进行gzip、br解压后在返回数据给用户？ (Issue #67)




 
源站已经处理文件并且响应：
 Content-Encoding: br
 
kangle节点作为边缘，然后给用户访问
 
用户端访问时，Accept-Encoding: gzip 声明未支持br，此时kangle是否会解压并且重新压缩成gzip返回，或者用户Accept-Encoding声明为空时，直接解压后的数据返回
 
如果在kangle上发生解压，过程是否在内存执行，是否会因为文件大小导致节点内存泄漏？有无办法禁用节点上的解压操作
 
测试，在源站存放30KB的文件，并且增加Content-Encoding: br响应头，此时用户端访问会产生400G的流量
 400Gbr.zip

**Comment by 1265578519** [comment]
那挺好，cloudflare那边就会把数据在CDN节点上解压后重新压缩在发送
