### ISSUE TITLE
black list

### ISSUE THREAD

**Issue by cdnfly365** [keengo99/kangle#68]
怎么看kangle的blacklist拉黑的ip有哪些，有api或者命令吗感谢

**Comment by 1265578519** [comment]
block_ip_cmd来获取黑名单ip，不对接防火墙的话，可以用命令来获取log文件
https://bbs.itzmx.com/thread-9269-1-1.html
```
echo ${ip} > /root/black_list.log
```

https://bbs.itzmx.com/thread-99558-1-1.html

**Comment by cdnfly365** [comment]
感谢小樱，我试试看

小樱 ***@***.***>于2024年7月21日 周日下午6:36写道：
