### ISSUE TITLE
主机的证书没有按照预期返回

### ISSUE THREAD

**Issue by funnycups** [keengo99/kangle#69]
创建两个主机，分别绑定域名a.com和b.com，并设置相应的ssl证书。
当访问a.com时，证书正常，但访问b.com，却会返回a.com的证书
将a.com所在主机的证书路径删除后，b.com正常访问，但把证书路径重新添加回去后，访问b.com又会返回a.com的证书信息

**Comment by 1265578519** [comment]
kangle禁止https ip访问，拒绝没有sni信息就不回复证书并且拦截响应错误信息

版本需求：3.6.0

部署方法：配置文件在https端口监听的listen中增加属性 reject_nosni='1'

效果
https://104.18.31.69/ 输出 ERR_SSL_VERSION_OR_CIPHER_MISMATCH

**Comment by 1265578519** [comment]
目前版本因为要支持sni协议来识别不同的站点，这样才能实现一台服务器支持多个https站点（现在没有强制校验证书是否吊销在输出给用户的功能选项，可以汇报给官方做个标记模块来实现），如果未部署证书的站点则会输出全局默认证书。
多个域名设置证书的方案不在端口监听处，而是在左侧虚拟主机里面单独为每个域名分配证书
例子如下
www.itzmx.com|server://nodes=192.168.1.2:80:10:1,192.168.1.3:80:10:1,192.168.1.4:80:10:1/error_count=1/error_try_time=30;www.itzmx.com.server.crt|www.itzmx.com.server.key
https://bbs.itzmx.com/thread-20013-1-1.html
https://bbs.itzmx.com/thread-17605-1-1.html

**Comment by funnycups** [comment]
> 目前版本因为要支持sni协议来识别不同的站点，这样才能实现一台服务器支持多个https站点（现在没有强制校验证书是否吊销在输出给用户的功能选项，可以汇报给官方做个标记模块来实现），如果未部署证书的站点则会输出全局默认证书。 多个域名设置证书的方案不在端口监听处，而是在左侧虚拟主机里面单独为每个域名分配证书 例子如下
> 
> ```
> www.itzmx.com|server://nodes=192.168.1.2:80:10:1,192.168.1.3:80:10:1,192.168.1.4:80:10:1/error_count=1/error_try_time=30;www.itzmx.com.server.crt|www.itzmx.com.server.key
> ```
> 
> https://bbs.itzmx.com/thread-20013-1-1.html https://bbs.itzmx.com/thread-17605-1-1.html

我就是在虚拟主机的设置里添加证书路径的，端口监听那里没有改过设置。两个虚拟主机分别绑定两个域名，但其中一个虚拟主机在访问时却始终只能得到另一个虚拟主机配置的证书，除非我把另一个虚拟主机的证书信息删去


针对b.com的主机，我删去主机设置里的证书和私钥设置，并绑定主机头b.com|server://nodes=127.0.0.1:2013s:10:1/error_count=1/error_try_time=30;/home/ssl.crt|/home/ssl.key，访问后仍然会给我返回a.com的证书
如果我把a.com的主机也删去证书和私钥设置，并绑定a.com|www;/home/cert.pem|/home/key.pem，则kangle将无法得到默认的证书文件，无法监听https端口，并提示SSL use certificate file []: Error: error:02000002:system library:OPENSSL_internal:No such file or directory

**Comment by 1265578519** [comment]
从你描述这个提示是因为你的证书密钥文件不正确，无法通过key成功加载ssl，可以联系证书颁发商给予apache的证书文件
或者使用kangle官方的autocert自动申请证书申请一个新证书
https://bbs.itzmx.com/thread-95877-1-1.html

**Comment by funnycups** [comment]
> 从你描述这个提示是因为你的证书密钥文件不正确，无法通过key成功加载ssl，可以联系证书颁发商给予apache的证书文件 或者使用kangle官方的autocert自动申请证书申请一个新证书 https://bbs.itzmx.com/thread-95877-1-1.html

证书文件应该是没问题的，我使用的是acme.sh生成的key-file和fullchain-file，而且如果我删去a.com所在主机配置的证书文件信息，那么我访问b.com可以得到正确的证书信息，也能够通过浏览器的证书校验。

**Comment by 1265578519** [comment]
> > 从你描述这个提示是因为你的证书密钥文件不正确，无法通过key成功加载ssl，可以联系证书颁发商给予apache的证书文件 或者使用kangle官方的autocert自动申请证书申请一个新证书 https://bbs.itzmx.com/thread-95877-1-1.html
> 
> 证书文件应该是没问题的，我使用的是acme.sh生成的key-file和fullchain-file，而且如果我删去a.com所在主机配置的证书文件信息，那么我访问b.com可以得到正确的证书信息，也能够通过浏览器的证书校验。


目前无法监听https端口的原因只有证书key无法加载成功，通过key解不出来crt引起的，你先试试换个证书呢？

**Comment by funnycups** [comment]
> > > 从你描述这个提示是因为你的证书密钥文件不正确，无法通过key成功加载ssl，可以联系证书颁发商给予apache的证书文件 或者使用kangle官方的autocert自动申请证书申请一个新证书 https://bbs.itzmx.com/thread-95877-1-1.html
> > 
> > 
> > 证书文件应该是没问题的，我使用的是acme.sh生成的key-file和fullchain-file，而且如果我删去a.com所在主机配置的证书文件信息，那么我访问b.com可以得到正确的证书信息，也能够通过浏览器的证书校验。
> 
> 目前无法监听https端口的原因只有证书key无法加载成功，通过key解不出来crt引起的，你先试试换个证书呢？

我发现kangle似乎确实没有正确识别到ssl证书，因为b.com的主机名在主机列表里不是绿色的，没有用ssl_enabled渲染。但我把a.com的证书删去后这个主机的名称又是绿色的

**Comment by 1265578519** [comment]
> 我发现kangle似乎确实没有正确识别到ssl证书，因为b.com的主机名在主机列表里不是绿色的，没有用ssl_enabled渲染。但我把a.com的证书删去后这个主机的名称又是绿色的

你这个证书是三个文件的nginx格式，kangle不支持这种格式的证书，需要用apache这种双文件的，第三个文件是通过额外的密钥去解锁key，由于三文件方式的证书所以就识别不到了

**Comment by funnycups** [comment]
> > 我发现kangle似乎确实没有正确识别到ssl证书，因为b.com的主机名在主机列表里不是绿色的，没有用ssl_enabled渲染。但我把a.com的证书删去后这个主机的名称又是绿色的
> 
> 你这个证书是三个文件的nginx格式，kangle不支持这种格式的证书，需要用apache这种双文件的，第三个文件是通过额外的密钥去解锁key，由于三文件方式的证书所以就识别不到了

应该是Nginx两个文件，apache三个文件吧？
另外，我现在使用autocert，发现如果在主机的证书设置中部署这个证书的话，会显示域名正确地部署了证书(域名是绿色的)，并且访问也正常了，但如果我重启kangle，域名又变回黑色，证书又不正常了，进入主机详情页面重新保存又可以用。我感觉应该是kangle的bug

**Comment by 1265578519** [comment]
> 但如果我重启kangle，域名又变回黑色，证书又不正常了，进入主机详情页面重新保存又可以用。我感觉应该是kangle的bug

重启后刚才操作的配置被复原的话，这个原因是因为你的这个虚拟主机不是在kangle上创建是，是使用api来创建，例如是在easypanel上创建的虚拟主机，那么要在easypanel上去操作，或者直接编辑vhd.db文件来实现修改

**Comment by funnycups** [comment]
> > 但如果我重启kangle，域名又变回黑色，证书又不正常了，进入主机详情页面重新保存又可以用。我感觉应该是kangle的bug
> 
> 重启后刚才操作的配置被复原的话，这个原因是因为你的这个虚拟主机不是在kangle上创建的，是使用api来创建，例如是在easypanel上创建的虚拟主机，那么要在easypanel上去操作，或者直接使用sqlitestudio编辑vhd.db文件来实现修改 这个不是bug，是kangle核心源代码里特别这么写的逻辑

没有，这个主机就是我直接在kangle上创建的，存储在config.xml里面的。我说的“进入主机详情页面重新保存”仅仅是进入详情页面然后点击确定而已，没有重新设置什么

**Comment by 1265578519** [comment]
那我这无法复现不知道是什么情况了，重启后config.xml不会被复原
至于acme.sh生成的证书有问题要联系他们issues反馈下怎么搞

**Comment by funnycups** [comment]
把两个主机的证书切换成autocert生成的证书后，仍然存在证书上的问题：重启kangle后，其中一个主机的ssl证书会失效，但进入主机设置页面重新保存一下，又会恢复。重载kangle配置则不存在类似问题。
此外，我有一个安装了3.5.21.16版本kangle的系统，也使用acme.sh生成的证书，但并未出现两个主机里有某个主机ssl无法正确加载的问题。

**Comment by 1265578519** [comment]
@keengo99 来检查一下看看能不能复现

**Comment by keengo99** [comment]
把证书还有配置文件什么的打包发给我测试一下。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月26日(周五) 晚上11:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [keengo99/kangle] 主机的证书没有按照预期返回 (Issue #69)




 
@keengo99 来检查一下看看能不能复现

**Comment by funnycups** [comment]
> 把证书还有配置文件什么的打包发给我测试一下。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年7月26日(周五) 晚上11:25 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [keengo99/kangle] 主机的证书没有按照预期返回 (Issue #69) @keengo99 来检查一下看看能不能复现 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

配置文件和证书：
[kangle.zip](https://github.com/user-attachments/files/16400649/kangle.zip)

**Comment by keengo99** [comment]
这个不是大问题,因为kangle的证书是按需加载的,你启动后如果没有访问这个域名,ssl将不会加载,所以ssl_enabled就会显示有问题,我提交了一个补丁,修复了这个问题.

**Comment by funnycups** [comment]
> 这个不是大问题,因为kangle的证书是按需加载的,你启动后如果没有访问这个域名,ssl将不会加载,所以ssl_enabled就会显示有问题,我提交了一个补丁,修复了这个问题.

请问这个按需加载的具体机制是怎么样的？目前虽然面板里显示是正确加载ssl证书的，但在重启kangle后访问域名仍然显示证书不正确，访问几次都不行，除非进入主机设置页面专门点击一次提交按钮

**Comment by keengo99** [comment]
我再研究一下看看



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月29日(周一) 晚上9:59
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [keengo99/kangle] 主机的证书没有按照预期返回 (Issue #69)




  
这个不是大问题,因为kangle的证书是按需加载的,你启动后如果没有访问这个域名,ssl将不会加载,所以ssl_enabled就会显示有问题,我提交了一个补丁,修复了这个问题.
  
请问这个按需加载的具体机制是怎么样的？目前虽然面板里显示是正确加载ssl证书的，但在重启kangle后访问域名仍然显示证书不正确，访问几次都不行，除非进入主机设置页面专门点击一次提交按钮

**Comment by keengo99** [comment]
已经修复



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月29日(周一) 晚上9:59
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [keengo99/kangle] 主机的证书没有按照预期返回 (Issue #69)




  
这个不是大问题,因为kangle的证书是按需加载的,你启动后如果没有访问这个域名,ssl将不会加载,所以ssl_enabled就会显示有问题,我提交了一个补丁,修复了这个问题.
  
请问这个按需加载的具体机制是怎么样的？目前虽然面板里显示是正确加载ssl证书的，但在重启kangle后访问域名仍然显示证书不正确，访问几次都不行，除非进入主机设置页面专门点击一次提交按钮

**Comment by 1265578519** [comment]
受影响只有仓库里面的3.6.0版本吗
https://github.com/keengo99/kangle/commit/9deef7a34ca18cce76a0596fe173feec8da1d4de

看了一下历史记录好像是从http3.0支持这次提交
https://github.com/keengo99/kangle/commit/7496a6696e5e145574c1cb4354a9901e881c0934

**Comment by keengo99** [comment]
是的，原来的版本没问题，中间改动太大，改出问题了！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月1日(周四) 上午8:23
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [keengo99/kangle] 主机的证书没有按照预期返回 (Issue #69)




 
受影响只有仓库里面的3.6.0版本吗
 9deef7a
 
看了一下历史记录好像是从http3.0支持这次提交
 7496a66
