### ISSUE TITLE
kangle对ip地址的https进行反代并且重写域名时，回源不应当发起sni信息

### ISSUE THREAD

**Issue by 1265578519** [keengo99/kangle#7]
kangle对ip地址的https进行反代并且重写域名时，回源不应当发起sni信息

例子，重写目标为
https://47.241.122.196/download/?fid=

![image](https://user-images.githubusercontent.com/6442439/157310155-4790273a-ddc9-417a-9773-9849891e2e41.png)

![image](https://user-images.githubusercontent.com/6442439/157310181-94e50527-665f-45bd-bf00-c5fbfb8777cc.png)

![2](https://user-images.githubusercontent.com/6442439/157310119-99a86c02-80dd-4a47-9697-7e39ea93848f.png)

可参考golang，curl，chrome等报文，如果当https地址是ip地址格式时候，应当不应该发起SNI
![image](https://user-images.githubusercontent.com/6442439/157315284-07334f74-3a30-4616-9e6f-d44e6556d19c.png)

同时ipv6地址作用https时候也不要发起sni，，随便找个ip来测试下发起信息 https://[2607:f2d8:4010:c::2]
![image](https://user-images.githubusercontent.com/6442439/157314033-7c8500f5-d179-4733-90a3-7fffc88d688c.png)

![image](https://user-images.githubusercontent.com/6442439/157313985-553373a2-093a-4e60-bc53-92f052875c8a.png)

**Comment by 1265578519** [comment]
![image](https://user-images.githubusercontent.com/6442439/157311757-c5fab3df-1ca6-4cc3-8db5-50b905d179ce.png)
![image](https://user-images.githubusercontent.com/6442439/157311834-1bda6414-8b62-4c3c-9516-16842a9f0111.png)
已知的解决flag模块，但是应当在代码层做判断为佳

**Comment by keengo99** [comment]
最新版本已经修复，请测试。
